// Netlify Function: dossier-review
// Handles two actions:
//   1. acknowledge  — records that the user acknowledged the Research Use Disclaimer
//   2. save_review  — saves a user's Confirmed/Rejected/Needs Research annotation
//   3. get_ack      — returns the user's current acknowledgment status
//   4. get_reviews  — returns all claim reviews for a dossier
//
// Requires a valid Supabase JWT in the Authorization header.

const SUPABASE_URL          = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL
const SUPABASE_SERVICE_KEY  = process.env.SUPABASE_SERVICE_ROLE_KEY
const RESEND_API_KEY        = process.env.RESEND_API_KEY
const DISCLAIMER_VERSION    = '1.0'

import { corsHeaders } from './_config.js'

// ─── Verify Supabase JWT ──────────────────────────────────────────────────────
async function verifyUser(authHeader) {
  if (!authHeader?.startsWith('Bearer ')) return null
  const token = authHeader.slice(7)
  const res = await fetch(`${SUPABASE_URL}/auth/v1/user`, {
    headers: {
      apikey: SUPABASE_SERVICE_KEY,
      Authorization: `Bearer ${token}`,
    },
  })
  if (!res.ok) return null
  return await res.json()
}

// ─── Supabase REST helper ─────────────────────────────────────────────────────
async function supabaseQuery(path, method = 'GET', body = null, params = '') {
  const url = `${SUPABASE_URL}/rest/v1/${path}${params}`
  const opts = {
    method,
    headers: {
      apikey: SUPABASE_SERVICE_KEY,
      Authorization: `Bearer ${SUPABASE_SERVICE_KEY}`,
      'Content-Type': 'application/json',
      Prefer: method === 'POST' ? 'return=representation' : 'return=minimal',
    },
  }
  if (body) opts.body = JSON.stringify(body)
  const res = await fetch(url, opts)
  const text = await res.text()
  let data = null
  try { data = JSON.parse(text) } catch {}
  return { ok: res.ok, status: res.status, data }
}

// ─── Send acknowledgment confirmation email via Resend ────────────────────────
async function sendAckEmail(email, acknowledgedAt) {
  if (!RESEND_API_KEY) return
  const dateStr = new Date(acknowledgedAt).toLocaleString('en-US', {
    timeZone: 'America/Chicago',
    dateStyle: 'full',
    timeStyle: 'short',
  })
  const html = `
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"></head>
    <body style="font-family:Arial,sans-serif;background:#f3f4f6;padding:32px 0;">
      <div style="max-width:560px;margin:0 auto;background:#ffffff;border-radius:12px;overflow:hidden;">
        <div style="background:#1e3a5f;padding:28px 32px;text-align:center;">
          <div style="font-family:'Georgia',serif;font-size:26px;color:#ffffff;letter-spacing:0.04em;">Badger Board</div>
          <div style="height:3px;background:linear-gradient(90deg,#b91c1c,#e5e7eb,#1d4ed8);margin-top:12px;border-radius:2px;"></div>
          <p style="color:#94a3b8;font-size:13px;margin:8px 0 0;">WI Political Intelligence</p>
        </div>
        <div style="padding:32px;">
          <h2 style="color:#1e3a5f;font-size:18px;margin:0 0 16px;">Research Use Disclaimer Acknowledged</h2>
          <p style="color:#374151;font-size:14px;line-height:1.7;margin:0 0 16px;">
            This email confirms that you have read and acknowledged the Badger Board <strong>Research Use Disclaimer</strong>
            at the date and time recorded below.
          </p>
          <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px;margin:0 0 20px;">
            <table style="width:100%;font-size:13px;color:#374151;border-collapse:collapse;">
              <tr>
                <td style="padding:4px 0;font-weight:600;width:140px;">Account:</td>
                <td>${email}</td>
              </tr>
              <tr>
                <td style="padding:4px 0;font-weight:600;">Acknowledged:</td>
                <td>${dateStr} (CT)</td>
              </tr>
              <tr>
                <td style="padding:4px 0;font-weight:600;">Disclaimer Version:</td>
                <td>${DISCLAIMER_VERSION}</td>
              </tr>
            </table>
          </div>
          <p style="color:#6b7280;font-size:12px;line-height:1.6;margin:0 0 16px;">
            By acknowledging, you confirmed that you understand this platform provides AI-assisted research tools
            for informational purposes only, that all information requires independent verification before use,
            and that you accept full responsibility for any use of content generated by this platform.
          </p>
          <p style="color:#6b7280;font-size:12px;line-height:1.6;margin:0;">
            Please retain this record. If you did not acknowledge this disclaimer, contact
            <a href="mailto:tony@thebluejackgroup.com" style="color:#1d4ed8;">tony@thebluejackgroup.com</a> immediately.
          </p>
        </div>
        <div style="background:#f8fafc;padding:16px 32px;border-top:1px solid #e5e7eb;text-align:center;">
          <p style="color:#9ca3af;font-size:11px;margin:0;">
            Badger Board · The Bluejack Group · badgerboardwi.com
          </p>
        </div>
      </div>
    </body>
    </html>`

  await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${RESEND_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: 'Badger Board <noreply@noreply.badgerboardwi.com>',   // must match _email.js FROM (verified Resend domain)
      to: [email],
      subject: 'Badger Board: Research Use Disclaimer Acknowledgment Recorded',
      html,
    }),
  }).catch(() => {}) // never let email failure break the acknowledgment
}

// ─── Handler ──────────────────────────────────────────────────────────────────
export const handler = async (event) => {
  const headers = corsHeaders(event.headers?.origin || event.headers?.Origin)

  if (event.httpMethod === 'OPTIONS') return { statusCode: 200, headers, body: '' }
  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, headers, body: JSON.stringify({ error: 'Method not allowed' }) }
  }

  // Verify auth
  const user = await verifyUser(event.headers?.authorization || event.headers?.Authorization)
  if (!user) {
    return { statusCode: 401, headers, body: JSON.stringify({ error: 'Unauthorized' }) }
  }

  let body
  try { body = JSON.parse(event.body) } catch {
    return { statusCode: 400, headers, body: JSON.stringify({ error: 'Invalid JSON' }) }
  }

  const { action } = body

  // ── acknowledge ─────────────────────────────────────────────────────────────
  if (action === 'acknowledge') {
    const now = new Date().toISOString()

    // Mark previous acknowledgments as not current
    await supabaseQuery(
      `dossier_acknowledgments?user_id=eq.${user.id}&is_current=eq.true`,
      'PATCH',
      { is_current: false }
    )

    // Insert new acknowledgment
    const { ok, data } = await supabaseQuery('dossier_acknowledgments', 'POST', {
      user_id:             user.id,
      user_email:          user.email,
      disclaimer_version:  DISCLAIMER_VERSION,
      acknowledged_at:     now,
      ip_address:          event.headers?.['x-forwarded-for']?.split(',')[0]?.trim() || null,
      user_agent:          event.headers?.['user-agent'] || null,
      is_current:          true,
    })

    if (!ok) {
      return { statusCode: 500, headers, body: JSON.stringify({ error: 'Failed to record acknowledgment' }) }
    }

    // Send confirmation email (non-blocking)
    sendAckEmail(user.email, now).catch(() => {})

    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({
        ok: true,
        acknowledged_at: now,
        disclaimer_version: DISCLAIMER_VERSION,
      }),
    }
  }

  // ── get_ack ──────────────────────────────────────────────────────────────────
  if (action === 'get_ack') {
    const { ok, data } = await supabaseQuery(
      `dossier_acknowledgments`,
      'GET',
      null,
      `?user_id=eq.${user.id}&is_current=eq.true&disclaimer_version=eq.${DISCLAIMER_VERSION}&limit=1`
    )

    const ack = Array.isArray(data) ? data[0] : null
    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({
        acknowledged: !!ack,
        acknowledged_at: ack?.acknowledged_at || null,
        disclaimer_version: DISCLAIMER_VERSION,
      }),
    }
  }

  // ── save_review ──────────────────────────────────────────────────────────────
  if (action === 'save_review') {
    const { dossier_id, section_id, claim_text, status, note } = body
    if (!dossier_id || !section_id || !claim_text || !status) {
      return { statusCode: 400, headers, body: JSON.stringify({ error: 'Missing required fields' }) }
    }
    const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
    if (!UUID.test(dossier_id) || !UUID.test(section_id)) {
      return { statusCode: 400, headers, body: JSON.stringify({ error: 'Invalid dossier_id or section_id' }) }
    }

    const validStatuses = ['confirmed', 'rejected', 'needs_research']
    if (!validStatuses.includes(status)) {
      return { statusCode: 400, headers, body: JSON.stringify({ error: 'Invalid status' }) }
    }

    const claimKey = claim_text.slice(0, 100)

    // Try update first, then insert (upsert via unique index)
    const checkRes = await supabaseQuery(
      `dossier_claim_reviews`,
      'GET',
      null,
      `?dossier_id=eq.${encodeURIComponent(dossier_id)}&user_id=eq.${user.id}&section_id=eq.${encodeURIComponent(section_id)}&claim_text=like.${encodeURIComponent(claimKey + '*')}&limit=1`
    )

    const existing = Array.isArray(checkRes.data) ? checkRes.data[0] : null

    if (existing) {
      // Update existing
      await supabaseQuery(
        `dossier_claim_reviews?id=eq.${existing.id}`,
        'PATCH',
        { status, note: note || null, updated_at: new Date().toISOString() }
      )
      return { statusCode: 200, headers, body: JSON.stringify({ ok: true, id: existing.id }) }
    }

    // Insert new
    const { ok, data } = await supabaseQuery('dossier_claim_reviews', 'POST', {
      dossier_id,
      user_id:    user.id,
      section_id,
      claim_text: claim_text.slice(0, 500),
      status,
      note: note || null,
    })

    if (!ok) {
      return { statusCode: 500, headers, body: JSON.stringify({ error: 'Failed to save review' }) }
    }

    return { statusCode: 200, headers, body: JSON.stringify({ ok: true }) }
  }

  // ── get_reviews ──────────────────────────────────────────────────────────────
  if (action === 'get_reviews') {
    const { dossier_id } = body
    const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
    if (!dossier_id || !UUID_RE.test(dossier_id)) {
      return { statusCode: 400, headers, body: JSON.stringify({ error: 'valid dossier_id required' }) }
    }

    const { ok, data } = await supabaseQuery(
      `dossier_claim_reviews`,
      'GET',
      null,
      `?dossier_id=eq.${encodeURIComponent(dossier_id)}&user_id=eq.${user.id}&order=reviewed_at.desc`
    )

    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({ ok: true, reviews: Array.isArray(data) ? data : [] }),
    }
  }

  return { statusCode: 400, headers, body: JSON.stringify({ error: 'Unknown action' }) }
}
