import React from 'react'
import { Link } from 'react-router-dom'
import { FileText, Shield, AlertTriangle, Scale, ChevronLeft } from 'lucide-react'
import BadgerBoardLogo from '../components/BadgerBoardLogo'

const DISCLAIMER_VERSION = '1.0'
const EFFECTIVE_DATE = 'March 1, 2025'
const ATTORNEY_NAME = 'Sarah Ruffi, J.D.'
const FIRM = 'Ruffi Legal Consulting LLC'
const PLATFORM = 'Badger Board'
const OPERATOR = 'The Bluejack Group'

export default function DossierDisclaimer() {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header bar */}
      <div className="bg-brand-navy text-white">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Scale className="w-5 h-5 text-brand-red" />
            <BadgerBoardLogo width={100} />
          </div>
          <div className="flex items-center gap-2">
            <Link to="/profiler" className="flex items-center gap-1.5 text-white/70 hover:text-white text-sm transition-colors">
              <ChevronLeft className="w-4 h-4" />
              Back to Profiler
            </Link>
          </div>
        </div>
      </div>

      {/* Document */}
      <div className="max-w-4xl mx-auto px-6 py-10">
        {/* Title block */}
        <div className="bg-white rounded-2xl border border-gray-200 shadow-sm p-8 mb-6">
          <div className="flex items-start gap-4">
            <div className="w-12 h-12 rounded-xl bg-brand-red/10 flex items-center justify-center flex-shrink-0">
              <FileText className="w-6 h-6 text-brand-red" />
            </div>
            <div className="flex-1">
              <div className="flex items-center gap-2 mb-1">
                <span className="text-xs font-semibold text-brand-red bg-brand-red/10 px-2.5 py-0.5 rounded-full uppercase tracking-wider">Legal Document — Version {DISCLAIMER_VERSION}</span>
              </div>
              <h1 className="text-2xl font-bold text-gray-900 mb-2">
                {PLATFORM} Research Use Disclaimer &amp; Terms of Authorized Use
              </h1>
              <div className="text-sm text-gray-500 space-y-0.5">
                <p>Effective Date: {EFFECTIVE_DATE}</p>
                <p>Prepared by: {ATTORNEY_NAME} · {FIRM}</p>
                <p>Platform Operator: {OPERATOR} · badgerboardwi.com</p>
              </div>
            </div>
          </div>

          <div className="mt-6 bg-amber-50 border border-amber-200 rounded-xl p-4">
            <div className="flex gap-3">
              <AlertTriangle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
              <div className="text-sm text-amber-800">
                <p className="font-semibold mb-1">READ CAREFULLY BEFORE ACCESSING ANY PROFILE</p>
                <p className="leading-relaxed">This document constitutes a legally binding agreement. By clicking "I Acknowledge &amp; Continue" on the Profile Access screen, you confirm that you have read, understood, and agreed to every provision below. If you do not agree, you may not access, view, copy, or use any content generated by this platform.</p>
              </div>
            </div>
          </div>
        </div>

        {/* Section 1 */}
        <Section number="1" title="Nature of the Service and AI Content Limitations">
          <p>
            {PLATFORM} is an AI-assisted political research and intelligence tool operated by {OPERATOR}.
            The platform employs artificial intelligence language models to compile, synthesize, and present
            information derived from publicly available sources. <strong>All AI-generated profiles, candidate reports,
            intelligence reports, and any other content generated by this platform (collectively, "AI-Generated
            Content") are produced by automated systems and have not been independently verified by any human
            researcher, journalist, attorney, or other qualified professional before delivery to you.</strong>
          </p>
          <p className="mt-3">
            AI-Generated Content is subject to significant known limitations, including but not limited to:
            factual inaccuracies; outdated information; hallucinated or fabricated citations; misidentification
            of persons, positions, or affiliations; erroneous political party attributions; and incorrect
            characterization of public statements or records. <strong>You acknowledge that AI systems, including
            those used by this platform, are not infallible and that errors are inherent to and expected from
            AI-generated output.</strong>
          </p>
          <p className="mt-3">
            Confidence-level badges (e.g., [KNOWN], [RESEARCH REQUIRED], [Verify], [Likely]) embedded in
            AI-Generated Content are themselves AI-generated assessments. They are provided as an organizational
            aid only and do not represent verified factual determinations. Items labeled [KNOWN] or [Confirmed]
            have not necessarily been confirmed by a human and should be independently verified before any use.
          </p>
        </Section>

        {/* Section 2 */}
        <Section number="2" title="Mandatory Independent Verification Requirement">
          <p>
            <strong>You are solely and absolutely responsible for independently verifying every piece of
            information contained in any AI-Generated Content before using, relying upon, sharing, publishing,
            or acting on that information in any manner.</strong> Independent verification means consulting
            primary sources, including but not limited to: Wisconsin Elections Commission (WEC) records;
            official government filings; court records; financial disclosure filings; direct confirmation
            with the subject or their authorized representative; and review by a qualified human professional
            appropriate to the subject matter (e.g., attorney, licensed private investigator, journalist).
          </p>
          <p className="mt-3">
            The platform's Section 8 "Verification Checklist" is provided as a starting-point framework
            only. Completing items on that checklist does not satisfy your independent verification
            obligation, nor does it constitute a warranty or representation by {OPERATOR} that the
            remaining information in the profile is accurate.
          </p>
        </Section>

        {/* Section 3 */}
        <Section number="3" title="Prohibition on Use in Formal Legal and Regulatory Proceedings">
          <p>
            AI-Generated Content from this platform <strong>may not be used as evidence, support material,
            or any form of substantive documentation in any formal legal proceeding, regulatory filing,
            administrative action, court filing, law enforcement referral, or election challenge</strong>
            without prior written authorization from {OPERATOR} and independent corroboration of every
            specific claim by a qualified human professional. Use of unverified AI-Generated Content in
            such proceedings may constitute a violation of applicable rules of evidence, professional
            conduct standards, and applicable law.
          </p>
        </Section>

        {/* Section 4 */}
        <Section number="4" title="Fair Credit Reporting Act (FCRA) Compliance — Prohibited Uses">
          <p>
            <strong>This platform is not a consumer reporting agency as defined by the Fair Credit
            Reporting Act, 15 U.S.C. § 1681 et seq. ("FCRA"), and the information provided through
            this platform does not constitute a "consumer report" for purposes of the FCRA.</strong>
            You expressly represent and warrant that you will not use AI-Generated Content from this
            platform for any purpose regulated by the FCRA, including but not limited to:
          </p>
          <ul className="mt-3 space-y-1.5 ml-4">
            <li>Evaluating a person's eligibility for credit, insurance, or employment;</li>
            <li>Tenant screening or housing eligibility determinations;</li>
            <li>Any other purpose constituting a "consumer report" under 15 U.S.C. § 1681a(d);</li>
            <li>Any purpose for which the FCRA requires a permissible purpose or adverse action notice.</li>
          </ul>
          <p className="mt-3">
            Use of this platform for FCRA-regulated purposes is strictly prohibited and constitutes a
            material breach of this Agreement. You agree to indemnify, defend, and hold harmless
            {OPERATOR} from any FCRA claims arising from your unauthorized use.
          </p>
        </Section>

        {/* Section 5 */}
        <Section number="5" title="Defamation, Invasion of Privacy, and Tortious Use — Wisconsin Law">
          <p>
            You acknowledge that publishing, distributing, broadcasting, or communicating false statements
            of fact about a living person or existing entity may constitute defamation under applicable
            law, including Wisconsin defamation law as codified and interpreted under <strong>Wis. Stat.
            § 895.05</strong> and related common law. In Wisconsin, certain categories of false statements
            — including false accusations of criminal conduct, allegations of conduct incompatible with
            one's business, trade, or profession, and accusations of a loathsome disease — may constitute
            defamation per se, exposing you to presumed and potentially substantial damages without proof
            of actual harm.
          </p>
          <p className="mt-3">
            You further acknowledge that AI-Generated Content may contain information that, if false or
            incomplete, could form the basis of defamation claims, false light invasion of privacy claims,
            tortious interference claims, or other civil causes of action. <strong>You, and not {OPERATOR},
            bear sole legal responsibility for any downstream communication or publication of AI-Generated
            Content.</strong> {OPERATOR} expressly disclaims all liability for defamation, invasion of
            privacy, or any other tortious act arising from your use of AI-Generated Content.
          </p>
          <p className="mt-3">
            You acknowledge that <strong>Section 230 of the Communications Decency Act, 47 U.S.C. § 230,
            does not shield AI-generated outputs from liability</strong> in the manner it protects
            traditional user-generated content platforms. This means that additional care is required
            before relying on, republishing, or acting on AI-Generated Content.
          </p>
        </Section>

        {/* Section 6 */}
        <Section number="6" title="Authorized Use — Political Research Purposes Only">
          <p>
            This platform is designed and licensed exclusively for use by political campaigns, political
            action committees, political consulting firms, government relations professionals, and other
            politically sophisticated users engaged in lawful political research and opposition research
            activities (<strong>"Authorized Users"</strong>). By accessing any profile, you represent
            and warrant that:
          </p>
          <ul className="mt-3 space-y-1.5 ml-4">
            <li>You are an Authorized User using this platform for lawful political research purposes;</li>
            <li>You possess sufficient professional expertise to evaluate, contextualize, and independently verify AI-Generated Content;</li>
            <li>You will not use AI-Generated Content to harass, intimidate, stalk, threaten, or target any individual;</li>
            <li>You will not use AI-Generated Content to engage in disinformation, manipulation, or deceptive practices;</li>
            <li>You will not republish raw, unverified AI-Generated Content in any publicly accessible communication, advertisement, or press material without independent verification;</li>
            <li>You will comply with all applicable federal, state, and local laws governing political campaigns, advertising, and communications.</li>
          </ul>
        </Section>

        {/* Section 7 */}
        <Section number="7" title="Assumption of Risk">
          <p>
            <strong>You expressly, voluntarily, and knowingly assume all risks associated with accessing,
            using, relying upon, sharing, or acting on AI-Generated Content produced by this platform.</strong>
            These risks include, without limitation: the risk that information is inaccurate, incomplete, or
            fabricated; the risk that use of such information causes harm to a third party; the risk of
            defamation liability; the risk of regulatory penalty; and the risk of reputational, financial,
            or other harm to you, your clients, or your organization. This assumption of risk is a knowing
            and material inducement for {OPERATOR} to grant you access to this platform.
          </p>
        </Section>

        {/* Section 8 */}
        <Section number="8" title="Indemnification">
          <p>
            You agree to defend, indemnify, and hold harmless {OPERATOR}, its affiliates, officers,
            directors, employees, contractors, agents, licensors, and service providers from and against
            any and all claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees
            (including reasonable attorneys' fees) arising out of or relating to: (a) your use of or
            reliance on AI-Generated Content; (b) any content you publish or communicate derived from
            AI-Generated Content; (c) your violation of any applicable law or regulation; (d) your
            violation of any provision of this Agreement; or (e) any claim by a third party arising
            from your use of this platform or its outputs.
          </p>
          <p className="mt-3">
            <strong>You further acknowledge and agree that you bear primary responsibility for all
            downstream use of AI-Generated Content. If any information in a profile or report is used
            in a manner that results in legal, regulatory, reputational, or other harm to any party
            — including the subject of the profile — you, and not {OPERATOR}, are liable for that harm.</strong>
          </p>
        </Section>

        {/* Section 9 */}
        <Section number="9" title="Disclaimer of Warranties">
          <p>
            ALL AI-GENERATED CONTENT AND PLATFORM SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE"
            WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMITTED BY
            APPLICABLE LAW, {OPERATOR.toUpperCase()} EXPRESSLY DISCLAIMS ALL WARRANTIES INCLUDING,
            WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
            PURPOSE, ACCURACY, COMPLETENESS, AND NON-INFRINGEMENT. {OPERATOR.toUpperCase()} DOES
            NOT WARRANT THAT ANY INFORMATION PROVIDED THROUGH THIS PLATFORM IS ACCURATE, RELIABLE,
            CURRENT, OR FREE FROM ERROR.
          </p>
        </Section>

        {/* Section 10 */}
        <Section number="10" title="Limitation of Liability">
          <p>
            TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL {OPERATOR.toUpperCase()}
            BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE
            DAMAGES ARISING OUT OF OR RELATED TO YOUR USE OF THIS PLATFORM OR AI-GENERATED CONTENT,
            REGARDLESS OF THE THEORY OF LIABILITY AND EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
          </p>
          <p className="mt-3">
            IN ALL CASES, {OPERATOR.toUpperCase()}'S MAXIMUM AGGREGATE LIABILITY TO YOU FOR ANY
            CLAIM ARISING OUT OF OR RELATED TO THIS AGREEMENT OR YOUR USE OF THE PLATFORM SHALL NOT
            EXCEED THE TOTAL SUBSCRIPTION FEES ACTUALLY PAID BY YOU TO {OPERATOR.toUpperCase()} IN
            THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM.
          </p>
        </Section>

        {/* Section 11 */}
        <Section number="11" title="Retraction and Correction Process">
          <p>
            If you become aware that AI-Generated Content contains materially false or defamatory
            information about a person or entity, you are obligated to: (a) immediately cease any
            use or distribution of the affected content; (b) notify {OPERATOR} at
            <strong> tony@thebluejackgroup.com</strong> with a detailed description of the alleged
            error; and (c) cooperate in good faith with {OPERATOR}'s investigation and any correction
            process. Failure to act on known false information does not reduce your liability for
            downstream harm.
          </p>
        </Section>

        {/* Section 12 */}
        <Section number="12" title="Versioning and Re-Acknowledgment">
          <p>
            {OPERATOR} reserves the right to update this Disclaimer at any time. Material changes will
            be indicated by an updated version number. When a new version is issued, all users will be
            required to re-acknowledge the updated Disclaimer before accessing any further AI-Generated
            Content. Your continued use of the platform after re-acknowledging constitutes your binding
            agreement to the updated terms. Your acknowledgment history is retained in our records as
            documentation of your informed consent.
          </p>
        </Section>

        {/* Section 13 */}
        <Section number="13" title="Governing Law and Dispute Resolution">
          <p>
            This Agreement shall be governed by and construed in accordance with the laws of the State
            of Wisconsin, without regard to its conflict of laws provisions. Any dispute arising out of
            or relating to this Agreement or your use of this platform shall be resolved exclusively in
            the state or federal courts located in Dane County, Wisconsin. You hereby consent to personal
            jurisdiction in those courts and waive any objection to venue.
          </p>
        </Section>

        {/* Section 14 */}
        <Section number="14" title="Entire Agreement; Severability">
          <p>
            This Disclaimer, together with the Badger Board Terms of Service, constitutes the entire
            agreement between you and {OPERATOR} with respect to your use of AI-Generated Content and
            the Profiler feature. If any provision of this Agreement is held to be invalid or unenforceable,
            the remaining provisions shall continue in full force and effect. No waiver of any provision
            shall be effective unless in writing and signed by an authorized representative of {OPERATOR}.
          </p>
        </Section>

        {/* Attorney Note */}
        <div className="bg-white rounded-2xl border border-gray-200 shadow-sm p-6 mb-6">
          <div className="flex gap-3">
            <Shield className="w-5 h-5 text-brand-navy flex-shrink-0 mt-0.5" />
            <div className="text-sm text-gray-600">
              <p className="font-semibold text-gray-900 mb-2">Attorney's Note</p>
              <p className="leading-relaxed mb-2">
                This Disclaimer has been prepared as a professional draft reflecting best practices for
                AI-generated content platforms providing political research tools. It is intended to
                establish clear boundaries of authorized use, apprise users of the inherent limitations
                of AI-generated information, and create a documented record of informed consent.
              </p>
              <p className="leading-relaxed mb-2">
                Users who are political professionals, campaign staff, or consultants using this platform
                in their professional capacity are presumed to be sophisticated users with the knowledge
                and resources to independently evaluate and verify AI-generated research before use. The
                sophisticated user doctrine may limit {OPERATOR}'s liability to users who can be expected,
                based on their professional background, to exercise judgment and discretion in relying on
                AI-Generated Content.
              </p>
              <p className="leading-relaxed text-gray-500 text-xs mt-3 italic">
                This document is a draft prepared for attorney review. It should be reviewed by qualified
                Wisconsin counsel before reliance. Nothing herein constitutes legal advice. — {ATTORNEY_NAME}, {FIRM}
              </p>
            </div>
          </div>
        </div>

        {/* Version footer */}
        <div className="text-center text-xs text-gray-400 pb-8">
          <p>Badger Board Research Use Disclaimer · Version {DISCLAIMER_VERSION} · Effective {EFFECTIVE_DATE}</p>
          <p className="mt-1">{OPERATOR} · badgerboardwi.com</p>
          <p className="mt-2">
            <Link to="/terms" className="text-gray-400 hover:text-gray-600 underline">Terms of Service</Link>
            {' · '}
            <Link to="/profiler" className="text-gray-400 hover:text-gray-600 underline">Return to Profiler</Link>
          </p>
        </div>
      </div>
    </div>
  )
}

function Section({ number, title, children }) {
  return (
    <div className="bg-white rounded-2xl border border-gray-200 shadow-sm p-6 mb-4">
      <div className="flex items-start gap-3 mb-3">
        <div className="w-7 h-7 rounded-lg bg-brand-navy/10 flex items-center justify-center flex-shrink-0 text-xs font-bold text-brand-navy mt-0.5">
          {number}
        </div>
        <h2 className="text-base font-bold text-gray-900 leading-snug">{title}</h2>
      </div>
      <div className="ml-10 text-sm text-gray-700 leading-relaxed">
        {children}
      </div>
    </div>
  )
}
